version: "3"
services:
  app:
    image: mattermost/focalboard
    container_name: focalboard
    volumes:
      - fbdata:/data/volumes/fbdata
    ports:
      - 80:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000

volumes:
  fbdata:
